'''
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?
'''

import time


pentagons = set(num * ((3 * num) - 1) / 2 for num in range(2, 5000))

def solution():
    for a in pentagons:
        for b in pentagons:
            if a + b in pentagons and a + 2 * b in pentagons:
                return int(a)


start_time = time.time()

print(solution())
print("Runtime: %s seconds" % (time.time() - start_time))