'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import time

triangles = set(num * (num + 1) / 2 for num in range(286, 100000))
pentagons = set(num * ((3 * num) - 1) / 2 for num in range(166, 100000))
hexagons = set(num * ((2 * num) - 1) for num in range(144, 100000))


def solution():
    triplets = triangles.intersection(pentagons).intersection(hexagons)
    return int(triplets.pop())


start_time = time.time()

print(solution())
print("Runtime: %s seconds" % (time.time() - start_time))